name: Production Environment Deployment

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    deploy-production:
        name: Production Environment Deployment
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Node.js setup
              uses: actions/setup-node@v4
              with:
                  node-version: '18.18.1'
                  cache: yarn

            - name: Yarn install package
              run: yarn install --frozen-lockfile

            - name: Setting up environment variables
              run: |
                  jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' <<< $SECRETS_CONTEXT > .env
              env:
                  SECRETS_CONTEXT: ${{ toJson(secrets) }}

            - name: App build
              id: build
              run: CI=false yarn run build

            - name: AWS Credentials setup
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-southeast-1

            - name: S3 bucket update
              run: |
                  aws s3 cp --recursive --region ap-southeast-1 ./dist "s3://$AWS_S3_BUCKET_NAME/widget"
              env:
                  AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}

            - name: CloudFront cache update
              run: |
                  aws cloudfront create-invalidation --distribution-id "$AWS_CLOUDFRONT_DISTRIBUTION_ID" --paths "/*"
              env:
                  AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}

            - name: Slack notification
              uses: 8398a7/action-slack@v3
              with:
                  status: ${{ job.status }}
                  author_name: Hippo River Widget Production Environment
                  mention: '<@dj>'
                  fields: repo,message,commit,author
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
              if: always()
